- hosts: superpi
  remote_user: pi
  become: yes
  serial:
    - 1
    - 3
  order: inventory
  tasks:
    - name: Reboot the server
      reboot:
        msg: "Ansible Reboot"
        connect_timeout: 5
        reboot_timeout: 120
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
