- hosts: superpi
  remote_user: ubuntu
  become: yes
  tasks:
    #Shut down password authentication for SSH
    - name: Shut Down Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin prohibit-password'
        line: PermitRootLogin no
    - name: Disable Password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes'
        line: PasswordAuthentication no
