#https://www.docker.com/blog/happy-pi-day-docker-raspberry-pi/
- hosts: superpi
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Add Docker repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu/ focal stable
        state: present
    - name: Install Docker service
      apt:
        update_cache: yes
        state: latest
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        group: docker
        append: yes
    - name: Start the Docker service
      systemd:
        state: started
        name: docker
