- hosts: superpi
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Complete system update
      apt:
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
